name: Build Android

on: pull_request

concurrency:
  group: ios-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'sapmachine'
          java-version: 21
      - name: Assemble
        run: ./gradlew assembleDebug