name: Build Android

on: [push, pull_request]

concurrency:
  group: android-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'sapmachine'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run lint
        run: ./gradlew spotlessCheck

      - name: Run build
        run: ./gradlew assemble --no-build-cache