name: Build iOS

on: pull_request

concurrency:
  group: ios-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'sapmachine'
          java-version: 21

      - name: Build iOS
        run: ./gradlew :iosApp:assembleRelease